# Generated by Django 5.2.12 on 2026-03-06 07:08

import diq.diq
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Chat', '0001_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('content', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chat.basechat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.baseuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=(models.Model, diq.diq.Dictify),
        ),
    ]
