# Generated by Django 5.2.12 on 2026-07-22 07:39

from django.db import migrations, models


def initialize_geocoding_status(apps, schema_editor):
    ImageMetadata = apps.get_model('Message', 'ImageMetadata')
    ImageMetadata.objects.exclude(address='').update(geocoding_status=1)
    ImageMetadata.objects.filter(latitude__isnull=True, longitude__isnull=True).update(geocoding_status=3)


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0005_imagemetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemetadata',
            name='geocoding_error',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='imagemetadata',
            name='geocoding_status',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.RunPython(initialize_geocoding_status, migrations.RunPython.noop),
    ]
