# Generated by Django 5.2.12 on 2026-07-24 15:43

import diq.diq
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0010_alter_message_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(db_index=True, default=0)),
                ('raw_avinfo', models.JSONField(blank=True, default=dict)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('pixel_width', models.PositiveIntegerField(blank=True, null=True)),
                ('pixel_height', models.PositiveIntegerField(blank=True, null=True)),
                ('frame_rate', models.FloatField(blank=True, null=True)),
                ('bit_rate', models.BigIntegerField(blank=True, null=True)),
                ('video_codec', models.CharField(blank=True, default='', max_length=64)),
                ('audio_codec', models.CharField(blank=True, default='', max_length=64)),
                ('make', models.CharField(blank=True, default='', max_length=255)),
                ('model', models.CharField(blank=True, default='', max_length=255)),
                ('lens_model', models.CharField(blank=True, default='', max_length=255)),
                ('software', models.CharField(blank=True, default='', max_length=255)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=500)),
                ('geocoding_provider', models.CharField(blank=True, default='', max_length=32)),
                ('geocoding_status', models.IntegerField(db_index=True, default=0)),
                ('geocoding_error', models.CharField(blank=True, default='', max_length=500)),
                ('error', models.CharField(blank=True, default='', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_metadata', to='Message.message')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
            bases=(models.Model, diq.diq.Dictify),
        ),
    ]
