# Generated by Django 5.2.12 on 2026-09-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0033_move_audio_transcript_to_media_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='submission_round',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='submission_visible_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='messageevent',
            name='type',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)]),
        ),
    ]
