# Generated by Django 5.2.12 on 2026-09-07 08:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Square', '0013_statement_comment_mentions_and_stickers'),
    ]

    operations = [
        migrations.CreateModel(
            name='QZoneUser',
            fields=[
                ('qq', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nickname', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'qzone_user',
            },
        ),
        migrations.CreateModel(
            name='QZonePost',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source_post_id', models.CharField(max_length=64)),
                ('content_raw', models.TextField(blank=True, default='')),
                ('content_text', models.TextField(blank=True, default='')),
                ('published_at', models.DateTimeField(db_index=True)),
                ('visibility', models.CharField(default='public', max_length=16)),
                ('media', models.JSONField(default=list)),
                ('source_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('statement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qzone_source', to='Square.statement')),
                ('author', models.ForeignKey(db_column='author_qq', on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='QZone.qzoneuser')),
            ],
            options={
                'db_table': 'qzone_post',
                'ordering': ('published_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='QZoneComment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content_raw', models.TextField(blank=True, default='')),
                ('published_at', models.DateTimeField(db_index=True)),
                ('source_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(blank=True, db_column='parent_comment_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='QZone.qzonecomment')),
                ('statement_comment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qzone_source', to='Square.statementcomment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='QZone.qzonepost')),
                ('author', models.ForeignKey(db_column='author_qq', on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='QZone.qzoneuser')),
                ('reply_to', models.ForeignKey(blank=True, db_column='reply_to_qq', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='targeted_comments', to='QZone.qzoneuser')),
            ],
            options={
                'db_table': 'qzone_comment',
                'ordering': ('published_at', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='qzonepost',
            constraint=models.UniqueConstraint(fields=('author', 'source_post_id'), name='unique_qzone_post_author_source'),
        ),
    ]
