# Generated by Django 5.2.12 on 2026-09-07 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0033_move_audio_transcript_to_media_asset'),
        ('QZone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QZoneMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('kind', models.CharField(max_length=16)),
                ('source_path', models.CharField(max_length=500)),
                ('source_url', models.CharField(blank=True, default='', max_length=1000)),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('content_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('ready', 'ready'), ('missing', 'missing'), ('failed', 'failed')], db_index=True, default='pending', max_length=16)),
                ('error', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='QZone.qzonecomment')),
                ('media_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qzone_import_items', to='Message.mediaasset')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='QZone.qzonepost')),
            ],
            options={
                'db_table': 'qzone_media',
                'ordering': ('id',),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('comment__isnull', True), ('post__isnull', False)), models.Q(('comment__isnull', False), ('post__isnull', True)), _connector='OR'), name='qzone_media_has_one_owner'), models.UniqueConstraint(fields=('post', 'position'), name='unique_qzone_post_media_position'), models.UniqueConstraint(fields=('comment', 'position'), name='unique_qzone_comment_media_position')],
            },
        ),
    ]
