# Generated by Django 5.2.12 on 2026-09-07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0033_move_audio_transcript_to_media_asset'),
        ('QZone', '0002_qzonemedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='QZoneEmoticon',
            fields=[
                ('code', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('source_path', models.CharField(blank=True, default='', max_length=500)),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('content_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('ready', 'ready'), ('missing', 'missing'), ('failed', 'failed')], db_index=True, default='pending', max_length=16)),
                ('error', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qzone_emoticons', to='Message.mediaasset')),
            ],
            options={
                'db_table': 'qzone_emoticon',
                'ordering': ('code',),
            },
        ),
        migrations.AddField(
            model_name='qzonepost',
            name='emoticons',
            field=models.ManyToManyField(blank=True, related_name='posts', to='QZone.qzoneemoticon'),
        ),
        migrations.AddField(
            model_name='qzonecomment',
            name='emoticons',
            field=models.ManyToManyField(blank=True, related_name='comments', to='QZone.qzoneemoticon'),
        ),
    ]
