from django.urls import path

from Chat.views import (
    ChatListView,
    DirectChatView,
    GroupChatView,
    GroupChatNameView,
    GroupChatMemberView,
    GroupChatOwnerView,
    GroupChatInviteRespondView,
    GroupChatInviteListView,
    GroupChatLeaveView,
    ChatReadView,
    ChatPreferenceView,
    SubmissionRecipientView,
    SubmissionStartView,
    SubmissionInviteReviewView,
    SubmissionSubmitView,
    SubmissionStatusView,
    SubmissionWithdrawView,
)

urlpatterns = [
    path('', ChatListView.as_view(), name='chat_list'),
    path('direct', DirectChatView.as_view(), name='direct_chat'),
    path('group', GroupChatView.as_view(), name='group_chat'),
    path('group/name', GroupChatNameView.as_view(), name='group_chat_name'),
    path('group/members', GroupChatMemberView.as_view(), name='group_chat_members'),
    path('group/owner', GroupChatOwnerView.as_view(), name='group_chat_owner'),
    path('group/invites', GroupChatInviteListView.as_view(), name='group_chat_invites'),
    path('group/invite/respond', GroupChatInviteRespondView.as_view(), name='group_chat_invite_respond'),
    path('group/leave', GroupChatLeaveView.as_view(), name='group_chat_leave'),
    path('read', ChatReadView.as_view(), name='chat_read'),
    path('preference', ChatPreferenceView.as_view(), name='chat_preference'),
    path('submissions/recipients', SubmissionRecipientView.as_view(), name='submission_recipients'),
    path('submissions/start', SubmissionStartView.as_view(), name='submission_start'),
    path('submissions/invites', SubmissionInviteReviewView.as_view(), name='submission_invite_review'),
    path('submissions/submit', SubmissionSubmitView.as_view(), name='submission_submit'),
    path('submissions/status', SubmissionStatusView.as_view(), name='submission_status'),
    path('submissions/withdraw', SubmissionWithdrawView.as_view(), name='submission_withdraw'),
]
