# Generated by Django 5.2.12 on 2026-09-07 11:26

import diq.diq
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0033_move_audio_transcript_to_media_asset'),
        ('Square', '0013_statement_comment_mentions_and_stickers'),
        ('User', '0076_qqidentity_user_account_kind_user_merged_into_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statementcomment',
            name='reply_to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_statement_comments', to='User.user'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='statementcomment',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='StatementCommentMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='Square.statementcomment')),
                ('media_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statement_comment_media_items', to='Message.mediaasset')),
            ],
            options={
                'ordering': ['position', 'id'],
                'constraints': [models.UniqueConstraint(fields=('comment', 'position'), name='unique_statement_comment_media_position')],
            },
            bases=(models.Model, diq.diq.Dictify),
        ),
    ]
