# Generated by Django 5.2.12 on 2026-03-06 07:08

import diq.diq
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.IntegerField(choices=[(0, 0), (1, 1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_chat_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.hostuser')),
            ],
            bases=(models.Model, diq.diq.Dictify),
        ),
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('basechat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Chat.basechat')),
                ('name', models.CharField(max_length=20)),
                ('guests', models.ManyToManyField(to='User.guestuser')),
            ],
            bases=('Chat.basechat',),
        ),
        migrations.CreateModel(
            name='SingleChat',
            fields=[
                ('basechat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Chat.basechat')),
                ('guest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='User.guestuser')),
            ],
            bases=('Chat.basechat',),
        ),
        migrations.CreateModel(
            name='ChatReadState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chat.basechat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.baseuser')),
            ],
            options={
                'unique_together': {('chat', 'user')},
            },
        ),
    ]
