# Generated by Django 5.2.12 on 2026-03-11 04:10

import diq.diq
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0001_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_group_chats', to='User.baseuser'),
        ),
        migrations.CreateModel(
            name='GroupChatInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)], db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='Chat.groupchat')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_invites', to='User.guestuser')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_group_invites', to='User.baseuser')),
            ],
            options={
                'unique_together': {('chat', 'guest')},
            },
            bases=(models.Model, diq.diq.Dictify),
        ),
    ]
