# Generated by Django 5.2.12 on 2026-09-02 00:54

import diq.diq
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0007_backfill_active_member_joined_at'),
        ('User', '0071_wechat_identity_per_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='purpose',
            field=models.IntegerField(choices=[(0, 0), (1, 1)], db_index=True, default=0),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_draft_id', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission_record', to='Chat.chat')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_submissions', to='User.user')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
            bases=(models.Model, diq.diq.Dictify),
        ),
    ]
