# Generated by Django 5.2.12 on 2026-09-02 01:46

import django.db.models.deletion
from django.db import migrations, models


def backfill_submission_roles(apps, schema_editor):
    Submission = apps.get_model('Chat', 'Submission')
    ChatMember = apps.get_model('Chat', 'ChatMember')
    for submission in Submission.objects.select_related('chat').iterator():
        submission.author_id = submission.chat.created_by_id
        submission.status = 1
        submission.submitted_at = submission.created_at
        submission.save(update_fields=['author_id', 'status', 'submitted_at'])
        ChatMember.objects.filter(chat_id=submission.chat_id).update(role=0)
        ChatMember.objects.filter(chat_id=submission.chat_id, user_id=submission.recipient_id).update(role=1)


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0008_chat_purpose_submission'),
        ('Square', '0012_squaremute'),
        ('User', '0071_wechat_identity_per_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authored_submissions', to='User.user'),
        ),
        migrations.AddField(
            model_name='submission',
            name='published_statement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_submissions', to='Square.statement'),
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_submission_roles, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='submission',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_submissions', to='User.user'),
        ),
    ]
