# Generated by Django 5.2.12 on 2026-09-05 12:46

import diq.diq
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0011_chatmember_submission_role'),
        ('User', '0074_harden_notification_delivery_dispatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(0, 0), (1, 1)], db_index=True)),
                ('status', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)], db_index=True, default=0)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_invites', to='Chat.chat')),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_submission_invites', to='User.user')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_submission_invites', to='User.user')),
            ],
            options={
                'indexes': [models.Index(fields=['chat', 'invitee', 'status'], name='submission_invitee_status')],
            },
            bases=(models.Model, diq.diq.Dictify),
        ),
    ]
