# Generated by Django 5.2.12 on 2026-09-09 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0012_submissioninvite'),
        ('User', '0077_user_chat_muted_permanently_user_chat_muted_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmember',
            name='chat_muted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_group_chat_mutes', to='User.user'),
        ),
        migrations.AddField(
            model_name='chatmember',
            name='chat_muted_permanently',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='chatmember',
            name='chat_muted_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
