# Generated by Django 5.2.12 on 2026-09-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0013_chatmember_chat_muted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='current_round',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
