# Generated by Django 5.2.12 on 2026-03-11 10:00

import Config.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True, validators=[Config.validators.ConfigValidator.key])),
                ('value', models.CharField(max_length=255, validators=[Config.validators.ConfigValidator.value])),
            ],
        ),
    ]
