# Generated by Django 5.2.12 on 2026-08-22 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Space', '0007_space_admin_phone_space_admin_phone_verified_at_and_more'),
        ('User', '0066_move_baxian_bubbles_to_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=80)),
                ('title_en', models.CharField(blank=True, default='', max_length=120)),
                ('summary', models.CharField(blank=True, default='', max_length=200)),
                ('summary_en', models.CharField(blank=True, default='', max_length=240)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField(db_index=True)),
                ('event_key', models.CharField(default='square.statement.publish', max_length=80)),
                ('daily_user_limit', models.PositiveSmallIntegerField(default=1)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.PositiveIntegerField()),
                ('resource_type', models.CharField(max_length=24)),
                ('reward_pool', models.JSONField(default=list)),
                ('reward_label', models.CharField(blank=True, default='', max_length=80)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='Activity.activitycampaign')),
            ],
            options={
                'ordering': ['threshold'],
            },
        ),
        migrations.CreateModel(
            name='SpaceActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_runs', to='Activity.activitycampaign')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='Space.space')),
            ],
        ),
        migrations.CreateModel(
            name='SpaceActivityReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(max_length=24)),
                ('reward_id', models.CharField(max_length=80)),
                ('resource_key', models.CharField(max_length=80)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_rewards', to='Activity.activitymilestone')),
                ('space_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='Activity.spaceactivity')),
            ],
        ),
        migrations.CreateModel(
            name='UserActivityProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_points', models.PositiveIntegerField(default=0)),
                ('available_points', models.PositiveIntegerField(default=0)),
                ('contributed_points', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='Activity.activitycampaign')),
                ('space_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='Activity.spaceactivity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_progress', to='User.user')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=80)),
                ('event_reference', models.CharField(blank=True, default='', max_length=80)),
                ('event_date', models.DateField(db_index=True)),
                ('points', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='Activity.activitycampaign')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='Activity.useractivityprogress')),
            ],
        ),
        migrations.AddConstraint(
            model_name='spaceactivityreward',
            constraint=models.UniqueConstraint(fields=('space_activity', 'milestone'), name='activity_space_milestone_unique'),
        ),
        migrations.AddConstraint(
            model_name='activitymilestone',
            constraint=models.UniqueConstraint(fields=('campaign', 'threshold'), name='activity_campaign_threshold_unique'),
        ),
        migrations.AddConstraint(
            model_name='spaceactivity',
            constraint=models.UniqueConstraint(fields=('campaign', 'space'), name='activity_campaign_space_unique'),
        ),
        migrations.AddConstraint(
            model_name='useractivityprogress',
            constraint=models.UniqueConstraint(fields=('campaign', 'user'), name='activity_campaign_user_unique'),
        ),
        migrations.AddConstraint(
            model_name='activityevent',
            constraint=models.UniqueConstraint(fields=('campaign', 'progress', 'event_key', 'event_date', 'event_reference'), name='activity_event_reference_unique'),
        ),
    ]
