# Generated by Django 5.2.12 on 2026-03-13 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Space', '0001_initial'),
        ('User', '0002_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='official_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='official_space', to='User.user'),
        ),
    ]
