# Generated by Django 5.2.12 on 2026-03-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Space', '0002_space_official_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='member_limit',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
