# Generated by Django 5.2.12 on 2026-09-02 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Space', '0008_spaceoperator'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='submission_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
