# Generated by Django 5.2.12 on 2026-09-07 11:26

import diq.diq
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Space', '0009_space_submission_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='qq_binding_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SpaceFeatureGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_key', models.CharField(choices=[('qq_identity_binding', 'qq_identity_binding')], max_length=64)),
                ('granted_by', models.EmailField(blank=True, default='', max_length=254)),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_grants', to='Space.space')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('space', 'feature_key'), name='unique_space_feature_grant')],
            },
            bases=(models.Model, diq.diq.Dictify),
        ),
    ]
