# Generated by Django 5.2.12 on 2026-03-06 07:08

import User.validators
import diq.diq
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(0, 0), (1, 1)])),
                ('offline_notification_interval', models.PositiveIntegerField(default=5, validators=[User.validators.BaseUserValidator.offline_notification_interval])),
                ('notification_channel', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0)),
                ('is_online', models.BooleanField(default=False)),
                ('last_heartbeat', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('bark', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salt', models.CharField(max_length=32)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            bases=(models.Model, diq.diq.Dictify),
        ),
        migrations.CreateModel(
            name='HostUser',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='User.baseuser')),
                ('name', models.CharField(max_length=20, unique=True, validators=[User.validators.BaseUserValidator.name])),
                ('lower_name', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=64, validators=[User.validators.BaseUserValidator.password])),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('subdomain', models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[User.validators.BaseUserValidator.subdomain])),
            ],
            bases=('User.baseuser',),
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='User.baseuser')),
            ],
        ),
        migrations.CreateModel(
            name='GuestUser',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='User.baseuser')),
                ('password', models.CharField(blank=True, max_length=64, null=True, validators=[User.validators.BaseUserValidator.password])),
                ('name', models.CharField(max_length=20, validators=[User.validators.BaseUserValidator.name])),
                ('lower_name', models.CharField(max_length=20)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to='User.hostuser')),
            ],
            options={
                'unique_together': {('lower_name', 'host')},
            },
            bases=('User.baseuser',),
        ),
    ]
