# Generated by Django 5.2.12 on 2026-03-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 0), (1, 1)], db_index=True, default=1),
        ),
    ]

