# Generated by Django 5.2.12 on 2026-03-11 02:00

import diq.diq
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], db_index=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_actors', to='User.baseuser')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_events', to='User.hostuser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_events', to='User.baseuser')),
            ],
            bases=(models.Model, diq.diq.Dictify),
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('enabled', models.BooleanField(default=False)),
                ('offline_threshold_minutes', models.PositiveIntegerField(default=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='User.baseuser')),
            ],
            options={
                'unique_together': {('user', 'channel')},
            },
            bases=(models.Model, diq.diq.Dictify),
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)])),
                ('status', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], db_index=True, default=0)),
                ('detail', models.CharField(blank=True, max_length=255, null=True)),
                ('attempted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='User.notificationevent')),
            ],
            bases=(models.Model, diq.diq.Dictify),
        ),
    ]
