# Generated by Django 5.2.12 on 2026-03-18

import User.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(
                default='en',
                max_length=16,
                validators=[User.validators.UserValidator.language],
            ),
        ),
    ]

