# Generated by Django 5.2.12 on 2026-03-11 03:00

import User.validators
import diq.diq
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_notification_center'),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', models.CharField(db_index=True, max_length=15, unique=True, validators=[User.validators.BaseUserValidator.subdomain])),
                ('group_square_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('official_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='space', to='User.hostuser')),
            ],
            bases=(models.Model, diq.diq.Dictify),
        ),
    ]
