# Generated by Django 5.2.12 on 2026-03-18

import User.validators
from django.db import migrations, models


MEMBER_WELCOME_MESSAGE_ZH = '我已同意你的好友申请，快来和我聊天吧～'
MEMBER_WELCOME_MESSAGE_EN = 'I accepted your friend request. Come chat with me!'
OFFICIAL_WELCOME_MESSAGE_ZH = '欢迎加入{space}！'
OFFICIAL_WELCOME_MESSAGE_EN = 'Welcome to {space}!'


def forwards(apps, schema_editor):
    User = apps.get_model('User', 'User')

    for user in User.objects.select_related('space').all().iterator():
        current = (user.welcome_message or '').strip()
        if current:
            continue

        lang = (user.language or 'en').strip().lower().replace('_', '-')
        normalized_language = 'zh-CN' if lang == 'zh-cn' else 'en'

        if user.role == 0:  # OFFICIAL
            if normalized_language == 'en':
                welcome_message = OFFICIAL_WELCOME_MESSAGE_EN.format(space=user.space.name)
            else:
                welcome_message = OFFICIAL_WELCOME_MESSAGE_ZH.format(space=user.space.name)
        else:
            welcome_message = MEMBER_WELCOME_MESSAGE_EN if normalized_language == 'en' else MEMBER_WELCOME_MESSAGE_ZH

        user.welcome_message = welcome_message
        user.save(update_fields=['welcome_message'])


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='welcome_message',
            field=models.CharField(
                default='',
                max_length=500,
                validators=[User.validators.UserValidator.welcome_message],
            ),
        ),
        migrations.RunPython(forwards, noop_reverse),
    ]

