# Generated by Django 5.2.12 on 2026-03-11 03:30

import diq.diq
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_space_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_requests', to='User.baseuser')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests', to='User.hostuser')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friend_requests', to='User.baseuser')),
            ],
            bases=(models.Model, diq.diq.Dictify),
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.CASCADE, related_name='friendships', to='User.hostuser')),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_as_user_1', to='User.baseuser')),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_as_user_2', to='User.baseuser')),
            ],
            options={
                'unique_together': {('host', 'user_1', 'user_2')},
            },
            bases=(models.Model, diq.diq.Dictify),
        ),
    ]
