# Generated by Django 5.2.12 on 2026-03-11 07:20

import User.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_friendship'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True, validators=[User.validators.ConfigValidator.key])),
                ('value', models.CharField(max_length=255, validators=[User.validators.ConfigValidator.value])),
            ],
        ),
    ]
