# Generated by Django 5.2.12 on 2026-03-11 08:05

import django.db.models.deletion
from django.db import migrations, models


def _backfill_account_levels(apps, schema_editor):
    BaseUser = apps.get_model('User', 'BaseUser')
    HostUser = apps.get_model('User', 'HostUser')
    GuestUser = apps.get_model('User', 'GuestUser')

    host_ids = HostUser.objects.values_list('id', flat=True)
    BaseUser.objects.filter(id__in=host_ids).update(account_level=1)

    guest_ids = GuestUser.objects.exclude(password__isnull=True).exclude(password='').values_list('id', flat=True)
    BaseUser.objects.filter(id__in=guest_ids).update(account_level=1)


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_config_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='account_level',
            field=models.IntegerField(choices=[(0, 0), (1, 1)], default=0),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(db_index=True, max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_codes', to='User.baseuser')),
            ],
        ),
        migrations.RunPython(_backfill_account_levels, migrations.RunPython.noop),
    ]
