# Generated by Django 5.2.12 on 2026-03-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_drop_email_verification_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userloginlog',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_uri',
            field=models.CharField(default='', max_length=255),
        ),
    ]
