# Generated by Django 5.2.12 on 2026-07-16 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_pushdevice_pushdelivery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pushdevice',
            options={},
        ),
    ]
