# Generated by Django 5.2.12 on 2026-08-19 16:33

import diq.diq
import django.db.models.deletion
from django.db import migrations, models


GROWTH_RESOURCES = [
    (1, 'background', 'background.default', 'default'), (1, 'bubble', 'bubble.default', 'default'), (1, 'frame', 'frame.none', 'none'),
    (2, 'background', 'background.paper', 'paper'), (2, 'bubble', 'bubble.comic', 'comic'), (2, 'frame', 'frame.orbit', 'orbit'),
    (3, 'identity', 'identity.level_tag', ''), (3, 'background', 'background.mint', 'mint'), (3, 'frame', 'frame.polaroid', 'polaroid'),
    (4, 'background', 'background.dusk', 'dusk'), (4, 'bubble', 'bubble.typewriter', 'typewriter'), (4, 'frame', 'frame.camera', 'camera'),
    (5, 'background', 'background.comic', 'comic'), (5, 'bubble', 'bubble.sticker', 'sticker'), (5, 'frame', 'frame.soundwave', 'soundwave'),
    (6, 'background', 'background.zen', 'zen'), (6, 'bubble', 'bubble.zen', 'zen'), (6, 'frame', 'frame.butterfly', 'butterfly'),
    (7, 'background', 'background.hero', 'hero'), (7, 'bubble', 'bubble.newspaper', 'newspaper'), (7, 'frame', 'frame.aurora', 'aurora'),
    (8, 'background', 'background.dragon', 'dragon'), (8, 'background', 'background.bauhaus', 'bauhaus'), (8, 'bubble', 'bubble.toybrick', 'toybrick'), (8, 'frame', 'frame.moon', 'moon'),
    (9, 'background', 'background.mosaic', 'mosaic'), (9, 'background', 'background.tidepool', 'tidepool'), (9, 'bubble', 'bubble.hero', 'hero'), (9, 'frame', 'frame.papercut', 'papercut'),
    (10, 'background', 'background.forest', 'forest'), (10, 'background', 'background.desert', 'desert'), (10, 'bubble', 'bubble.bauhaus', 'bauhaus'), (10, 'frame', 'frame.comet', 'comet'),
    (11, 'background', 'background.sunrise', 'sunrise'), (11, 'background', 'background.snowfield', 'snowfield'), (11, 'bubble', 'bubble.receipt', 'receipt'), (11, 'frame', 'frame.snowfall', 'snowfall'),
    (12, 'background', 'background.sakura', 'sakura'), (12, 'background', 'background.midnight', 'midnight'), (12, 'bubble', 'bubble.dragon', 'dragon'), (12, 'frame', 'frame.portal', 'portal'),
    (13, 'background', 'background.rain', 'rain'), (13, 'background', 'background.galaxy', 'galaxy'), (13, 'bubble', 'bubble.mosaic', 'mosaic'), (13, 'frame', 'frame.mechanical', 'mechanical'),
    (14, 'background', 'background.aurora_sky', 'aurora-sky'), (14, 'background', 'background.linen', 'linen'), (14, 'background', 'background.terrazzo', 'terrazzo'),
    (15, 'background', 'background.blueprint', 'blueprint'), (15, 'background', 'background.newsprint', 'newsprint'), (15, 'background', 'background.hologram', 'hologram'),
    (16, 'background', 'background.arcade', 'arcade'), (16, 'background', 'background.jazz', 'jazz'), (16, 'bubble', 'bubble.niko', 'niko'), (16, 'frame', 'frame.niko', 'niko-run'),
    (17, 'background', 'background.spaceport', 'spaceport'), (17, 'background', 'background.candy', 'candy'), (17, 'bubble', 'bubble.fufu', 'fufu'), (17, 'frame', 'frame.fufu', 'fufu-wave'),
    (18, 'background', 'background.noir', 'noir-film'), (18, 'bubble', 'bubble.baxian_lv', 'baxian-lv'), (18, 'bubble', 'bubble.baxian_zhongli', 'baxian-zhongli'), (18, 'bubble', 'bubble.baxian_he', 'baxian-he'),
]

VIP_RESOURCES = [
    ('vip', 'vip.permanent', 'founding-100'), ('bubble', 'bubble.vip', 'vip'), ('frame', 'frame.vip', 'vip'),
    ('statement', 'statement.vip', 'vip'), ('bubble', 'bubble.niko.vip', 'niko'), ('bubble', 'bubble.fufu.vip', 'fufu'),
    ('frame', 'frame.niko.vip', 'niko-run'), ('frame', 'frame.fufu.vip', 'fufu-wave'),
    ('statement', 'statement.niko.vip', 'niko'), ('statement', 'statement.fufu.vip', 'fufu'),
]


def backfill_resource_inventory(apps, schema_editor):
    User = apps.get_model('User', 'User')
    Inventory = apps.get_model('User', 'UserResourceInventory')
    VipClaim = apps.get_model('User', 'PermanentVipClaim')
    vip_claims = {claim.user_id: claim for claim in VipClaim.objects.all().iterator()}
    rows = []
    for user in User.objects.filter(is_deleted=False).iterator():
        level = 18 if user.role == 0 else max(1, user.growth_level, user.growth_acknowledged_level)
        rows.extend(Inventory(
            user_id=user.id,
            resource_type=resource_type,
            reward_id=reward_id,
            resource_key=resource_key,
            source='growth',
            source_reference=f'level:{reward_level}',
        ) for reward_level, resource_type, reward_id, resource_key in GROWTH_RESOURCES if reward_level <= level)
        claim = vip_claims.get(user.id)
        if claim is not None or user.is_permanent_vip:
            slot = claim.slot if claim is not None else None
            rows.extend(Inventory(
                user_id=user.id,
                resource_type=resource_type,
                reward_id=reward_id,
                resource_key=resource_key,
                source='vip_campaign',
                source_reference='founding-100',
                metadata={'slot': slot} if slot is not None else {},
            ) for resource_type, reward_id, resource_key in VIP_RESOURCES)
    Inventory.objects.bulk_create(rows, ignore_conflicts=True, batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0058_remove_notification_custom_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResourceInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('background', 'background'), ('bubble', 'bubble'), ('frame', 'frame'), ('statement', 'statement'), ('identity', 'identity'), ('vip', 'vip')], db_index=True, max_length=24)),
                ('reward_id', models.CharField(max_length=80)),
                ('resource_key', models.CharField(blank=True, default='', max_length=80)),
                ('source', models.CharField(choices=[('growth', 'growth'), ('vip_campaign', 'vip_campaign'), ('system', 'system')], db_index=True, max_length=24)),
                ('source_reference', models.CharField(blank=True, default='', max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_inventory', to='User.user')),
            ],
            bases=(models.Model, diq.diq.Dictify),
        ),
        migrations.RunPython(backfill_resource_inventory, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='PermanentVipClaim',
        ),
        migrations.AddIndex(
            model_name='userresourceinventory',
            index=models.Index(fields=['user', 'resource_type', 'resource_key'], name='user_resource_lookup'),
        ),
        migrations.AddConstraint(
            model_name='userresourceinventory',
            constraint=models.UniqueConstraint(fields=('user', 'reward_id'), name='user_resource_inventory_unique'),
        ),
    ]
