# Generated by Django 5.2.12 on 2026-08-19 18:16

import diq.diq
import django.db.models.deletion
from django.db import migrations, models


def migrate_legacy_bark_endpoints(apps, schema_editor):
    User = apps.get_model('User', 'User')
    Endpoint = apps.get_model('User', 'InstantNotificationEndpoint')
    rows = User.objects.filter(bark__isnull=False, bark_verified_at__isnull=False).exclude(bark='')
    Endpoint.objects.bulk_create([
        Endpoint(
            user_id=user.id,
            provider='bark',
            target=user.bark,
            enabled=True,
            verified_at=user.bark_verified_at,
        )
        for user in rows.iterator()
    ], ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0059_user_resource_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstantNotificationEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('bark', 'bark'), ('ntfy', 'ntfy'), ('gotify', 'gotify')], max_length=16)),
                ('target', models.CharField(max_length=500)),
                ('secret', models.CharField(blank=True, max_length=500, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instant_notification_endpoints', to='User.user')),
            ],
            bases=(models.Model, diq.diq.Dictify),
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='instant_endpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='User.instantnotificationendpoint'),
        ),
        migrations.CreateModel(
            name='InstantNotificationVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('bark', 'bark'), ('ntfy', 'ntfy'), ('gotify', 'gotify')], max_length=16)),
                ('target', models.CharField(max_length=500)),
                ('secret', models.CharField(blank=True, max_length=500, null=True)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instant_notification_verifications', to='User.user')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
            bases=(models.Model, diq.diq.Dictify),
        ),
        migrations.AddConstraint(
            model_name='instantnotificationendpoint',
            constraint=models.UniqueConstraint(fields=('user', 'provider'), name='unique_user_instant_provider'),
        ),
        migrations.RunPython(migrate_legacy_bark_endpoints, migrations.RunPython.noop),
    ]
