# Generated by Django 5.2.12 on 2026-08-27 12:45

import diq.diq
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0069_unify_notification_deliveries'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('chats.changed', 'chats.changed'), ('friends.changed', 'friends.changed'), ('friend_requests.changed', 'friend_requests.changed')], db_index=True, max_length=32)),
                ('resource_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_events', to='User.user')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'id'], name='user_state_user_id_idx')],
            },
            bases=(models.Model, diq.diq.Dictify),
        ),
    ]
