# Generated by Django 5.2.12 on 2026-09-04 13:37

from django.db import migrations, models


def populate_delivery_routes(apps, schema_editor):
    Delivery = apps.get_model('User', 'NotificationDelivery')
    status_priority = {1: 0, 4: 1, 2: 2, 3: 3, 0: 4}
    keepers = []
    duplicate_ids = []

    def flush_batches(force=False):
        if keepers and (force or len(keepers) >= 500):
            Delivery.objects.bulk_update(keepers, ['route_key'], batch_size=500)
            keepers.clear()
        if duplicate_ids and (force or len(duplicate_ids) >= 500):
            Delivery.objects.filter(id__in=duplicate_ids).delete()
            duplicate_ids.clear()

    def consume_event(groups):
        for route_key, deliveries in groups.items():
            deliveries.sort(key=lambda item: (status_priority.get(item.status, 5), item.id))
            keeper, *duplicates = deliveries
            keeper.route_key = route_key
            keepers.append(keeper)
            duplicate_ids.extend(item.id for item in duplicates)
        flush_batches()

    current_event_id = None
    event_groups = {}
    for delivery in Delivery.objects.all().only(
        'id', 'event_id', 'channel', 'instant_endpoint_id', 'web_subscription_id', 'status',
    ).order_by('event_id', 'id').iterator(chunk_size=2000):
        if current_event_id is not None and delivery.event_id != current_event_id:
            consume_event(event_groups)
            event_groups = {}
        current_event_id = delivery.event_id
        if delivery.web_subscription_id:
            route_key = f'web:{delivery.web_subscription_id}'
        elif delivery.instant_endpoint_id:
            route_key = f'instant:{delivery.instant_endpoint_id}'
        else:
            route_key = f'channel:{delivery.channel}'
        event_groups.setdefault(route_key, []).append(delivery)
    if event_groups:
        consume_event(event_groups)
    flush_batches(force=True)


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0073_alter_notificationevent_event_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationdelivery',
            options={},
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='route_key',
            field=models.CharField(db_index=True, default='channel', max_length=80),
        ),
        migrations.AlterField(
            model_name='notificationdelivery',
            name='status',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], db_index=True, default=0),
        ),
        migrations.RunPython(populate_delivery_routes, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='notificationdelivery',
            constraint=models.UniqueConstraint(fields=('event', 'route_key'), name='unique_notification_delivery_route'),
        ),
    ]
