# Generated by Django 5.2.12 on 2026-09-07 08:16

import diq.diq
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Space', '0009_space_submission_enabled'),
        ('User', '0075_normalize_email_notification_thresholds'),
    ]

    operations = [
        migrations.CreateModel(
            name='QQIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qq', models.CharField(max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            bases=(models.Model, diq.diq.Dictify),
        ),
        migrations.AddField(
            model_name='user',
            name='account_kind',
            field=models.CharField(choices=[('member', 'member'), ('imported_placeholder', 'imported_placeholder')], db_index=True, default='member', max_length=24),
        ),
        migrations.AddField(
            model_name='user',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_legacy_users', to='User.user'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('account_kind', 'member'), ('is_deleted', True), _connector='OR'), name='imported_placeholder_is_not_active'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('merged_into__isnull', True), ('account_kind', 'imported_placeholder'), _connector='OR'), name='merged_user_is_imported_placeholder'),
        ),
        migrations.AddField(
            model_name='qqidentity',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qq_identities', to='Space.space'),
        ),
        migrations.AddField(
            model_name='qqidentity',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qq_identity', to='User.user'),
        ),
        migrations.AddConstraint(
            model_name='qqidentity',
            constraint=models.UniqueConstraint(fields=('space', 'qq'), name='unique_qq_identity_space'),
        ),
    ]
