# Generated by Django 5.2.12 on 2026-09-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0076_qqidentity_user_account_kind_user_merged_into_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_muted_permanently',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='chat_muted_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
