from django.utils.translation import gettext_lazy as _
from smartdjango import Code, Error


@Error.register
class SquareErrors:
    NOT_EXISTS = Error(message=_('Statement does not exist'), code=Code.NotFound)
    PUBLISH_REQUIRES_VERIFICATION = Error(message=_('Verify your email before publishing'), code=Code.Forbidden)
    CONTENT_REQUIRED = Error(message=_('Add text, photos, or a voice recording'), code=Code.BadRequest)
    TEXT_TOO_LONG = Error(message=_('A statement can contain at most 140 characters'), code=Code.BadRequest)
    MEDIA_INVALID = Error(message=_('Invalid statement attachment'), code=Code.BadRequest)
    IMAGE_LIMIT_EXCEEDED = Error(message=_('A statement can contain at most 9 photos'), code=Code.BadRequest)
    AUDIO_LIMIT_EXCEEDED = Error(message=_('A statement can contain only one voice recording'), code=Code.BadRequest)
    AUDIO_DURATION_INVALID = Error(message=_('Voice recording cannot exceed 60 seconds'), code=Code.BadRequest)
    VISIBILITY_INVALID = Error(message=_('Invalid statement visibility'), code=Code.BadRequest)
    LOCATION_INVALID = Error(message=_('Invalid statement location'), code=Code.BadRequest)
    COMMENT_REQUIRED = Error(message=_('Comment cannot be empty'), code=Code.BadRequest)
    COMMENT_TOO_LONG = Error(message=_('A comment can contain at most 140 characters'), code=Code.BadRequest)
    DAILY_LIMIT_REACHED = Error(message=_('Daily square limit reached'), code=Code.Forbidden)
    WEEKLY_LIMIT_REACHED = Error(message=_('Weekly square limit reached'), code=Code.Forbidden)
    ANONYMOUS_WEEKLY_LIMIT_REACHED = Error(message=_('Weekly anonymous statement limit reached'), code=Code.Forbidden)
    ANONYMOUS_REQUIRES_EXPLORE = Error(message=_('Anonymous statements require Explore to be enabled'), code=Code.Forbidden)
    ANONYMOUS_VISIBILITY_INVALID = Error(message=_('Anonymous statements must be visible in Explore'), code=Code.BadRequest)
    ANONYMOUS_COMMENT_FORBIDDEN = Error(message=_('Only the anonymous statement author can comment anonymously'), code=Code.Forbidden)
    AUDIO_LEVEL_REQUIRED = Error(message=_('Voice statements unlock at LV6'), code=Code.Forbidden)
    VIDEO_LEVEL_REQUIRED = Error(message=_('Video statements unlock at LV10'), code=Code.Forbidden)
    VIDEO_LIMIT_EXCEEDED = Error(message=_('A statement can contain only one video'), code=Code.BadRequest)
    DELETE_FORBIDDEN = Error(message=_('You cannot delete this statement'), code=Code.Forbidden)
    COMMENT_DELETE_FORBIDDEN = Error(message=_('You cannot delete this comment'), code=Code.Forbidden)
    PIN_FORBIDDEN = Error(message=_('Only the official account can pin its own statement'), code=Code.Forbidden)
    CHAT_RECORD_FORBIDDEN = Error(message=_('Only the official account can publish chat records'), code=Code.Forbidden)
    CHAT_RECORD_EXCLUSIVE = Error(message=_('Chat records cannot be combined with other attachments'), code=Code.BadRequest)
    MUTE_FORBIDDEN = Error(message=_('Only the official account can mute Square members'), code=Code.Forbidden)
    MUTE_TARGET_INVALID = Error(message=_('This member cannot be muted'), code=Code.BadRequest)
    MUTE_REASON_REQUIRED = Error(message=_('A mute reason is required'), code=Code.BadRequest)
    MUTE_DURATION_INVALID = Error(message=_('Invalid mute duration'), code=Code.BadRequest)
    MUTED = Error(message=_('You are currently muted from publishing or commenting in Square'), code=Code.Forbidden)
