from django.urls import path

from User.views import (
    HeartbeatView,
    UserMeView,
    UserEmojiUsageView,
    RefreshView,
    LogoutView,
    NotificationPreferenceView,
    UserWebReminderPreferenceView,
    UserGestureLockPreferenceView,
    WebPushSubscriptionView,
    PasswordView,
    PasswordRecoveryLookupView,
    PasswordRecoveryCodeView,
    PasswordRecoveryVerifyView,
    PasswordRecoveryResetView,
    ContactVerificationCodeRequestView,
    ContactBindingConfirmView,
    WelcomeMessageView,
    UserNameView,
    AvatarPresetView,
    AvatarCustomUploadView,
    AvatarCustomView,
    AccountSwitchListView,
    AccountSwitchTicketView,
    AccountSwitchExchangeView,
    PrivateAccountView,
    ContactUnbindView,
    UserGrowthEventView,
    UserGrowthAcknowledgementView,
    PermanentVipCampaignView,
    PlazaGreetingView,
    ChatBackgroundUploadView,
    ChatBackgroundView,
    UserPersonalizationView,
    UserLanguagePreferenceView,
)

urlpatterns = [
    path('heartbeat', HeartbeatView.as_view(), name='heartbeat'),
    path('me', UserMeView.as_view(), name='user me'),
    path('me/emoji-usage', UserEmojiUsageView.as_view(), name='user emoji usage'),
    path('me/growth-events', UserGrowthEventView.as_view(), name='user growth event'),
    path('me/growth', UserGrowthAcknowledgementView.as_view(), name='user growth acknowledgement'),
    path('me/permanent-vip', PermanentVipCampaignView.as_view(), name='permanent vip campaign'),
    path('refresh', RefreshView.as_view(), name='token refresh'),
    path('logout', LogoutView.as_view(), name='token revoke'),
    path('me/switch-accounts', AccountSwitchListView.as_view(), name='account switch list'),
    path('me/switch-account', AccountSwitchTicketView.as_view(), name='account switch ticket'),
    path('switch-account/exchange', AccountSwitchExchangeView.as_view(), name='account switch exchange'),
    path('me/private-account', PrivateAccountView.as_view(), name='private account'),
    path('me/notification-prefs', NotificationPreferenceView.as_view(), name='notification prefs'),
    path('me/web-reminder-prefs', UserWebReminderPreferenceView.as_view(), name='web reminder prefs'),
    path('me/gesture-lock', UserGestureLockPreferenceView.as_view(), name='gesture lock prefs'),
    path('me/web-push', WebPushSubscriptionView.as_view(), name='web push subscriptions'),
    path('me/password', PasswordView.as_view(), name='password'),
    path('password-recovery/lookup', PasswordRecoveryLookupView.as_view(), name='password recovery lookup'),
    path('password-recovery/code', PasswordRecoveryCodeView.as_view(), name='password recovery code'),
    path('password-recovery/verify', PasswordRecoveryVerifyView.as_view(), name='password recovery verify'),
    path('password-recovery/reset', PasswordRecoveryResetView.as_view(), name='password recovery reset'),
    path('me/contact-code', ContactVerificationCodeRequestView.as_view(), name='contact verification code'),
    path('me/bind-contact', ContactBindingConfirmView.as_view(), name='contact bind confirm'),
    path('me/unbind-contact', ContactUnbindView.as_view(), name='contact unbind'),
    path('me/name', UserNameView.as_view(), name='user name'),
    path('me/welcome-message', WelcomeMessageView.as_view(), name='welcome message'),
    path('me/plaza-greeting', PlazaGreetingView.as_view(), name='plaza greeting'),
    path('me/avatar/preset', AvatarPresetView.as_view(), name='avatar preset'),
    path('me/avatar/custom/upload', AvatarCustomUploadView.as_view(), name='avatar custom upload'),
    path('me/avatar/custom', AvatarCustomView.as_view(), name='avatar custom'),
    path('me/chat-background/upload', ChatBackgroundUploadView.as_view(), name='chat background upload'),
    path('me/chat-background', ChatBackgroundView.as_view(), name='chat background'),
    path('me/personalization', UserPersonalizationView.as_view(), name='user personalization'),
    path('me/language', UserLanguagePreferenceView.as_view(), name='user language preference'),
]
